# Generated by Django 5.2.12 on 2026-03-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('match_date', models.DateTimeField()),
            ],
        ),
    ]
